### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aamna10** [vedantnarayan/Circus#1]
![image](https://user-images.githubusercontent.com/31211804/29599558-2abd76f6-87ee-11e7-95b2-ba38e2f310ba.png)
****

**Comment by ravedata** [comment]
Please install django and chatterbot.

To install , use the following steps 
1. open the command prompt
2. navigate to the directory where the python(script) is installed e.g cd c:/Python/Scripts
3. type pip install chatterbot and enter.

use similar process for django.
